sky:
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: mine-dev
    access-key-secret: mYA3WxBiKvvLZyuIpHsIof0rsyjbTp
    access-key-id: LTAI5tNjznCTaeCuFQY2xdSm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xyZ.2448123830
  redis:
    host: localhost
    port: 6379